use crate::contracts::{PathEdgeKind, Route};

pub(crate) fn render(filtered: &[(String, Vec<&Route>)]) -> String {
    let mut out = String::new();
    out.push_str("# Generated by tophql\n");
    out.push_str("# Routes formatted as GraphQL query templates\n\n");

    for (type_name, routes) in filtered {
        for (i, route) in routes.iter().enumerate() {
            let verdict = format!("{:?}", route.verdict).to_uppercase();
            let entry = route.witness.entry_field_id.trim_start_matches("field:");

            // Comment header
            out.push_str(&format!(
                "# [{verdict}] Route {} — {}\n",
                i + 1,
                entry
            ));
            if let Some(sel) = &route.selector {
                out.push_str(&format!("# Selector: {} ({})\n", sel.arg_path, sel.type_ref.display));
            }
            out.push_str(&format!("# Path: {}\n", route.witness.display_projection));

            // Build query
            out.push_str(&emit_query(route, type_name, i + 1));
            out.push_str("\n\n");
        }
    }
    out
}

fn emit_query(route: &Route, type_name: &str, index: usize) -> String {
    let op_name = format!("Test{}_{}", type_name, index);

    let (var_decl, injected_args) = match &route.selector {
        None => (String::new(), String::new()),
        Some(sel) => {
            let var_type = &sel.type_ref.display;
            if sel.input_path.is_empty() {
                // Direct argument: event(id: $seed1)
                let arg_name = sel.arg_path.rsplit('.').next().unwrap_or("id");
                (
                    format!("($seed1: {var_type})"),
                    format!("({arg_name}: $seed1)"),
                )
            } else {
                // Nested input: events(filters: { ids: $seed1 })
                let root_arg = sel.root_arg_ref
                    .trim_start_matches("arg:")
                    .rsplit('.')
                    .next()
                    .unwrap_or("input");
                let wrapped = wrap_input_path(&sel.input_path, "$seed1");
                (
                    format!("($seed1: {var_type})"),
                    format!("({root_arg}: {wrapped})"),
                )
            }
        }
    };

    // Build selection set from witness edges
    let body = emit_body_from_edges(route, &injected_args);

    format!("query {op_name}{var_decl} {{\n{body}}}\n")
}

/// Build the nested query body by walking witness edges.
fn emit_body_from_edges(route: &Route, injected_args: &str) -> String {
    let edges = &route.witness.edges;
    if edges.is_empty() {
        return format!("  # (empty witness)\n");
    }

    // We need to build a nested structure.
    // Strategy: group consecutive type-condition edges with their next field.
    // Each field edge opens a block; type condition edges become inline fragments.

    let mut lines: Vec<String> = Vec::new();
    let mut depth = 1usize;
    let indent = |d: usize| "  ".repeat(d);

    let mut pending_type_conditions: Vec<String> = Vec::new();

    for (idx, edge) in edges.iter().enumerate() {
        let is_last = idx == edges.len() - 1;

        match edge.kind {
            PathEdgeKind::TypeCondition => {
                let type_name = edge.target_type_id.trim_start_matches("type:");
                pending_type_conditions.push(type_name.to_string());
            }
            PathEdgeKind::Field => {
                let field_name = edge
                    .field_id
                    .as_deref()
                    .and_then(|fid| fid.rsplit('.').next())
                    .unwrap_or("?");

                // Open pending type conditions first
                for type_name in pending_type_conditions.drain(..) {
                    lines.push(format!("{}... on {} {{", indent(depth), type_name));
                    depth += 1;
                }

                // Args only on the first field that needs them
                let args = if idx == 0 && !injected_args.is_empty() {
                    injected_args.to_string()
                } else {
                    String::new()
                };

                if is_last {
                    // Terminal field — add __typename + id, close all open blocks
                    lines.push(format!("{}{field_name}{args} {{", indent(depth)));
                    depth += 1;
                    lines.push(format!("{}__typename", indent(depth)));
                    lines.push(format!("{}id", indent(depth)));
                    // Close terminal field
                    depth -= 1;
                    lines.push(format!("{}}}", indent(depth)));
                    // Close any open type conditions
                    while depth > 1 {
                        depth -= 1;
                        lines.push(format!("{}}}", indent(depth)));
                    }
                } else {
                    // Non-terminal field — open block
                    lines.push(format!("{}{field_name}{args} {{", indent(depth)));
                    depth += 1;

                    // For connection types with a nodes field coming next, we don't need
                    // to add a "nodes" level — it will come as the next edge.
                }
            }
        }
    }

    // Safety: close any remaining open blocks (shouldn't happen with valid witnesses)
    while depth > 1 {
        depth -= 1;
        lines.push(format!("{}}}", indent(depth)));
    }

    lines.join("\n") + "\n"
}

fn wrap_input_path(path: &[String], var: &str) -> String {
    if path.is_empty() {
        return var.to_string();
    }
    let inner = wrap_input_path(&path[1..], var);
    format!("{{ {}: {} }}", path[0], inner)
}
